version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: conn-pty:latest
    environment:
      - NODE_ENV=production
      - OIDC_ISSUER
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - OIDC_REDIRECT_URI
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - db:/app/data

volumes:
  db:
    driver: local