[package]
name = "ssh-client-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "WebAssembly-based SSH client transport over WebSocket (pairs with server-side SSH proxy)"
authors = ["conn-pty maintainers"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = [
  "WebSocket",
  "MessageEvent",
  "ErrorEvent",
  "CloseEvent",
  "BinaryType",
  "Event"
] }