name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  code-build-ci-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Installing Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Building with Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Build CI
        run: |
          bun install
          bun run build
