name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME_API: conn-pty-api
  IMAGE_NAME_WEB: conn-pty-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for API
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME_API }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_API }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest

      - name: Extract metadata (tags, labels) for Web
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME_WEB }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_WEB }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: api
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta_api.outputs.labels }}
          tags: ${{ steps.meta_api.outputs.tags }}

      - name: Build and push Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: web
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta_web.outputs.labels }}
          tags: ${{ steps.meta_web.outputs.tags }}