name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME_APP: conn-pty

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for App
        id: meta_app
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME_APP }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_APP }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=tag
            type=raw,value=latest
            author=${{ github.actor }}
            date={{date 'YYYY-MM-DDTHH:mm:ssZ'}}
            commit={{sha}}

      - name: Build and push App image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: app
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta_app.outputs.labels }}
          tags: ${{ steps.meta_app.outputs.tags }}